### ISSUE TITLE
And when there is multiple sensors ?

### ISSUE THREAD

**Issue by VELD-Dev** [arduino-libraries/Arduino_GroveI2C_Ultrasonic#1]
How do we do when there is multiple sensors ? Any example for that ?

**Comment by gbr1** [comment]
Hi @VELD-Dev !
This library is written to support a M5Stack ultrasonic sensor which is bundled with our [Science Kit R3](https://www.arduino.cc/education/science-kit-r3/)

Unfortunately the hardware of this sensor doens't allow to have multiple of them (the sensor has only one possible address).

> Note: you can still use multiple sensors if you have multiple I2C (Wire, Wire1, Wire2, etc) on your Arduino board or use an I2C multiplexer
